project_id = "broeyaqgxkaqfjxjgrnw"

[functions.helpdesk]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false

[functions.script-assist]
verify_jwt = false

[functions.storyboard-assist]
verify_jwt = false